---
version: '3'
services:
    s3dataproducer:
        image: 'imagehub.cdc.gov:5989/edh/s3dataproducer'
        container_name: s3dataproducer
        environment:
            - 'PIPELINE_NAME=EIPPLUS'
            - 'GROUP_NAME=S3PRODUCER01'
            - 'OUTGOING_TOPIC_NAME=FDD.EIP.Source'
            - 'ERROR_TOPIC_NAME=eip-error'
            - 'KAFKA_BROKERS=sdl-dev01.biotech.cdc.gov:9092'
            - 'POLL_INTERVAL_MILLIS=2000'
            - 'S3_BUCKET_NAME=eip-plus-messages-dev'
            - 'S3_ACCESS_KEY=AKIAIHX6U5QGJDZGPVIA'
            - 'S3_SECRET=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'
            - 'SQS_URL=https://sqs.us-east-1.amazonaws.com/626636711996/eip-legacy-dev'
            - 'SCHEMA_REGISTRY_URL=http://sdl-dev01.biotech.cdc.gov:8081'     
        ports:
            - '10006:10006'
        networks:
            - sdh_nw 
networks:
    sdh_nw:
        driver: bridge
